spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bettracker
    username: bettracker
    password: bettracker123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-plateform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080
  adress: 0.0.0.0

jwt:
  secret: bettracker2026SuperSecretKeyPourSignerLesTokensJWT
  expiration: 604800000 #7 jours
